### ISSUE TITLE
List of test returns only one test when there are many

### ISSUE THREAD

**Issue by hiendtech** [vtunr/VTunit#4]
`python vtunit/vtunit.py build --list `
returns
1 test found :
         AL4_parameters

When there are many tests. They are running properly when running with build --cmake --run

Filters don't work too.

**Comment by vtunr** [comment]
@hiendtech filter is based on list, so if list is not working, filter won't too. I'll check soon and will provide a fix, thanks for the report.

**Comment by vtunr** [comment]
Can you test https://github.com/vtunr/VTunit/commit/2f084f61f0d87d0dc633b2aae5b89697a077c13d ?
